# Generated by Django 5.2.1 on 2025-05-25 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='children',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TEACHER', 'Docente'), ('STUDENT', 'Alumno'), ('PARENT', 'Padre')], max_length=10),
        ),
    ]
